FROM debian:bullseye

RUN apt update && apt upgrade

RUN apt install php7.4-fpm -y curl -y systemctl -y
RUN apt-get update && apt-get install -y php-fpm
RUN apt-get update && apt-get install -y php-mysql
RUN apt-get update && apt-get install -y mariadb-client

COPY my.cnf /etc/php7.4/fpm/pool.d/www.conf

RUN mkdir -p /run/php


COPY installwp.sh /
RUN chmod +x /installwp.sh


CMD ["bash", "/installwp.sh"]