FROM debian:bullseye

RUN apt update && apt upgrade && apt install mariadb-server -y

RUN apt install systemctl -y



COPY ./conf /etc/mysql/my.cnf


COPY script.sh /
RUN chmod +x script.sh

CMD ["./script.sh"]

