FROM debian:bullseye

RUN apt update && apt upgrade && apt install mariadb-server -y

RUN apt install systemctl -y



COPY ./conf /etc/mysql/my.cnf


RUN mkdir -p /var/run/mysqld/
RUN mkdir -p run/mysqld/
RUN touch /var/run/mysqld/mysqld.pid
RUN touch /var/run/mysqld/mysqld.sock
RUN chown mysql:mysql -R /var/run/mysqld
RUN chown mysql:mysql -R run/mysqld
COPY script.sh /
RUN chmod +x script.sh

CMD ["./script.sh"]

