FROM debian:bullseye

RUN apt update && apt install nginx -y && apt install openssl -y

COPY nginx.conf /etc/nginx/conf.d/inception.conf

RUN    openssl genrsa -out /etc/ssl/private/ssl_private_key.pem 2048
RUN    openssl req -new -key /etc/ssl/private/ssl_private_key.pem -out csr.pem -subj "/C=MA/ST=khouribga/L=khouribga/O=1337/OU=student/CN=LEET"
RUN    openssl x509 -req -days 365 -in csr.pem -signkey  /etc/ssl/private/ssl_private_key.pem -out /etc/ssl/certs/ssl_certificate.pem  && rm -rf csr.pem

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
